# NumPyを使った配列演算

* 演算が高速 (C++/Fortran並に)
* 行列演算、テンソル演算を簡潔に記述

## 配列の生成

In [1]:
import numpy as np

a = np.zeros((100,100)) #Create a new ndarray and fill it with zeros.

l = np.array([1, 4, 16, 64]) #Convert a list to a ndarray.
print(l)

b = np.array(a)  #Create a new ndarray with the same elements.

b = np.zeros_like(a)

b = a.copy()     #Make a copy
print(b.shape)
b[0,0] = 100
print(a[0,0], b[0,0])

a = np.linspace(0.0, 1.0, 10)
print(a)

a = np.array([n**2 for n in range(10)])
print(a)

[ 1  4 16 64]
(100, 100)
0.0 100.0
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[ 0  1  4  9 16 25 36 49 64 81]


## Viewの作成

In [2]:
N = 10
a = np.arange(1,N+1)
print(a)

#Create a view
b = a
print(b)
b[0] = 10000
print(a)

#Creating a view by basic indexing
b = a[3:5]
print(b[0], a[3])

#print(a[3:])
#print(a[3::2])
#print(a[3:6:2])
#a[3::2] = 1 
#print(a)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[10000     2     3     4     5     6     7     8     9    10]
4 4


In [3]:
#Create a view by reshape
N = 4
a = np.zeros((N,N)); print(a)

print(a.reshape(N**2))
b = a.reshape(N**2)
for i in range(N):
    a[i,0] = i
print(a)
print(b)
print(np.reshape(a,N**2))
print( a.reshape((2,2,2,2)) )

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [2. 0. 0. 0.]
 [3. 0. 0. 0.]]
[0. 0. 0. 0. 1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0.]
[[[[0. 0.]
   [0. 0.]]

  [[1. 0.]
   [0. 0.]]]


 [[[2. 0.]
   [0. 0.]]

  [[3. 0.]
   [0. 0.]]]]


In [4]:
N = 4
a = np.arange(N**2).reshape((N,N)).T
print(a)
np.conj(1.0+1.0J)

[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


(1-1j)

## 要素毎の演算

In [5]:
a = np.arange(0,10); print(a)

b = 2*a; print(b)

b += a; print(b)

b = b**2; print(b)

a = np.linspace(0.0, 2*np.pi, 10); print(a)
b = np.sin(a); print(b)
print(np.sum(b))

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]
[ 0  3  6  9 12 15 18 21 24 27]
[  0   9  36  81 144 225 324 441 576 729]
[0.         0.6981317  1.3962634  2.0943951  2.7925268  3.4906585
 4.1887902  4.88692191 5.58505361 6.28318531]
[ 0.00000000e+00  6.42787610e-01  9.84807753e-01  8.66025404e-01
  3.42020143e-01 -3.42020143e-01 -8.66025404e-01 -9.84807753e-01
 -6.42787610e-01 -2.44929360e-16]
8.813754755807632e-17


## 行列積

In [6]:
#import random

N = 2
a = np.random.rand(2*N**2).reshape((N,2*N))
print(a)

b = np.random.rand(2*N**2).reshape((2*N,N))
print(b)

print(a.shape, b.shape)

print(a@b)

[[0.31054486 0.1802281  0.74722034 0.82451045]
 [0.06589378 0.77689607 0.67287515 0.97249389]]
[[0.79706591 0.43745869]
 [0.39947994 0.05121717]
 [0.69750209 0.52419549]
 [0.0284718  0.3824479 ]]
(2, 4) (4, 2)
[[0.86418528 0.85210315]
 [0.85989656 0.7932626 ]]


## 線形代数

In [7]:
print(a.shape)
U,s,Vt = np.linalg.svd(a,full_matrices=False)
print(U.shape)
print(s.shape)
print(Vt.shape)

print("a=", a)
print("a=", U@np.diag(s)@Vt)

(2, 4)
(2, 2)
(2,)
(2, 4)
a= [[0.31054486 0.1802281  0.74722034 0.82451045]
 [0.06589378 0.77689607 0.67287515 0.97249389]]
a= [[0.31054486 0.1802281  0.74722034 0.82451045]
 [0.06589378 0.77689607 0.67287515 0.97249389]]


In [20]:
N = 5
A = np.random.rand(N**2).reshape((N,N))
A = A + A.transpose()
print(A)
evals, evecs = np.linalg.eigh(A)
#print(evals)
#print(evecs)
diag_mat = np.diag(evals)
A_reconstructed = evecs@diag_mat@evecs.transpose()
print(A_reconstructed)

[[1.64109927 0.79018811 0.58921985 1.84203249 1.22688237]
 [0.79018811 0.41760317 1.29435884 1.3213709  0.48733007]
 [0.58921985 1.29435884 1.23751645 0.37604454 1.74620629]
 [1.84203249 1.3213709  0.37604454 1.82912261 0.81708619]
 [1.22688237 0.48733007 1.74620629 0.81708619 1.99723772]]
[[1.64109927 0.79018811 0.58921985 1.84203249 1.22688237]
 [0.79018811 0.41760317 1.29435884 1.3213709  0.48733007]
 [0.58921985 1.29435884 1.23751645 0.37604454 1.74620629]
 [1.84203249 1.3213709  0.37604454 1.82912261 0.81708619]
 [1.22688237 0.48733007 1.74620629 0.81708619 1.99723772]]


## IO

In [8]:
np.save("a.npy", a)
b = np.load("a.npy")

In [9]:
N = 1000000
x = np.linspace(0, 1, N)
print((4/N)*np.sum(np.sqrt(1-x**2)))

#r = 0.0
#for i in range(N):
#    r += np.sqrt(1-x[i]**2)
#print((4/N)*r)

3.1415915108211565
