In [3]:
import numpy as np

In [2]:
def myfunc(x, y):
    print("called with ", x, y)
    return x * y

In [4]:
myfunc(4, 10)

called with  4 10


40

In [6]:
def myfunc2(x, y):
    return np.sin(x) * np.sin(y)

In [10]:
def factorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * factorial(n-1)


In [ ]:
factorial(4)

In [13]:
def factorial_loop(n):
    if n == 0 or n == 1:
        return 1
    
    r = 1
    for x in range(2,n+1):
        r *= x
    return r

factorial_loop(3)

6

In [18]:
#from scipy.special import factorial
#factorial(4)

In [28]:
a = np.zeros((2,2))

In [29]:
a

array([[0., 0.],
       [0., 0.]])

In [30]:
a[0, 1] = 2

In [32]:
print(a[0,1])
a

2.0


array([[0., 2.],
       [0., 0.]])

In [35]:
for i in range(2):
    for j in range(2):
        print(i,j)
        a[i, j] = i + 2*j
a

0 0
0 1
1 0
1 1


array([[0., 2.],
       [1., 3.]])

In [36]:
a @ a

array([[ 2.,  6.],
       [ 3., 11.]])

In [39]:
b = np.zeros((2, 2), dtype=complex)

In [52]:
a = np.array([1,2, 1000, 100])
a

array([   1,    2, 1000,  100])

In [53]:
a[0], a[1] = a[1], a[0]
a

array([   2,    1, 1000,  100])

In [43]:
for j in range(2):
    a[0, j] = 100
a

array([[100., 100.],
       [  1.,   3.]])

In [46]:
a[0, :] = 200
a

array([[200., 200.],
       [  1.,   3.]])

In [37]:
a * a

array([[0., 4.],
       [1., 9.]])