In [5]:
from __future__ import print_function
import numpy as np

10進数と2進数

In [6]:
N = 5

for i in range(2**5):
    print(i, bin(i))

0 0b0
1 0b1
2 0b10
3 0b11
4 0b100
5 0b101
6 0b110
7 0b111
8 0b1000
9 0b1001
10 0b1010
11 0b1011
12 0b1100
13 0b1101
14 0b1110
15 0b1111
16 0b10000
17 0b10001
18 0b10010
19 0b10011
20 0b10100
21 0b10101
22 0b10110
23 0b10111
24 0b11000
25 0b11001
26 0b11010
27 0b11011
28 0b11100
29 0b11101
30 0b11110
31 0b11111


整数の各bitを右から求める
シフト演算 (&)については、
https://qiita.com/7shi/items/41d262ca11ea16d85abc

In [18]:
def bits(some_int, num_bits):
    bits = np.empty(num_bits, dtype=int)
    int_shifted = some_int
    for i in range(num_bits):
        bits[i] = int_shifted & 1
        int_shifted = int_shifted >> 1
    return bits

some_int = 12

print(bits(some_int, 4))
print(bin(some_int))
    

[0 0 1 1]
0b1100


すべてのスピン状態を機械的に生成できる

In [19]:
# Number of spins
Ns = 5
for i in range(2**Ns):
    print(bits(i, Ns))

[0 0 0 0 0]
[1 0 0 0 0]
[0 1 0 0 0]
[1 1 0 0 0]
[0 0 1 0 0]
[1 0 1 0 0]
[0 1 1 0 0]
[1 1 1 0 0]
[0 0 0 1 0]
[1 0 0 1 0]
[0 1 0 1 0]
[1 1 0 1 0]
[0 0 1 1 0]
[1 0 1 1 0]
[0 1 1 1 0]
[1 1 1 1 0]
[0 0 0 0 1]
[1 0 0 0 1]
[0 1 0 0 1]
[1 1 0 0 1]
[0 0 1 0 1]
[1 0 1 0 1]
[0 1 1 0 1]
[1 1 1 0 1]
[0 0 0 1 1]
[1 0 0 1 1]
[0 1 0 1 1]
[1 1 0 1 1]
[0 0 1 1 1]
[1 0 1 1 1]
[0 1 1 1 1]
[1 1 1 1 1]
